language: go

go:
  - 1.x

before_install:
  - env GO111MODULE=on go get -v ./...
  
script:
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
